services:
  db:
    image: postgres
    container_name: interview-db
    ports:
      - "5434:5432"
    env_file:
      - <env_file_name> # ğŸ“ TODO: Specify filename
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
